---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Screenshot_2019-08-20 Periodization Training for Sports - Google
      Play/Screenshot_2019-08-20 Periodization Training for Sports - Google Play.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/78218/articles/384769/master/file/figures/Screenshot_2019-08-20%20Periodization%20Training%20for%20Sports%20-%20Google%20Play/Screenshot_2019-08-20%20Periodization%20Training%20for%20Sports%20-%20Google%20Play.png"
    folder_url: "/users/78218/articles/384769/master/folder/figures/Screenshot_2019-08-20
      Periodization Training for Sports - Google Play"
