---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Core plan/Core plan.xlsx
    type: table
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/78218/articles/384769/master/file/figures/Core%20plan/Core%20plan.xlsx"
    folder_url: "/users/78218/articles/384769/master/folder/figures/Core plan"
    treatFirstLineAsHeader: true
