---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/weight,fat,muscle(4)/weight,fat,muscle(5).png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/78218/articles/384769/master/folder/figures/weight,fat,muscle(4)"
    url: "/users/78218/articles/384769/master/file/figures/weight,fat,muscle(4)/weight,fat,muscle(5).png"
